# HaHa 密码安全配置
haha:
  security:
    password:
      enabled: false
      encoding-id: bcrypt
      
      # BCrypt 配置
      bcrypt:
        strength: 12
      
      # Argon2 配置
      argon2:
        salt-length: 16
        hash-length: 32
        parallelism: 1
        memory: 4096
        iterations: 3
      
      # SCrypt 配置
      scrypt:
        cpu-cost: 16384
        memory-cost: 8
        parallelization: 1
        key-length: 32
        salt-length: 64
      
      # PBKDF2 配置
      pbkdf2:
        algorithm: PBKDF2WithHmacSHA256
        iterations: 310000
        salt-length: 16
        hash-length: 32
      
      # 密码强度验证
      strength:
        enabled: true
        min-length: 8
        max-length: 128
        require-uppercase: true
        require-lowercase: true
        require-digit: true
        require-special-char: true
        forbidden-sequences:
          - "123456"
          - "abcdef"
          - "qwerty"
        common-passwords-file: "classpath:common-passwords.txt"
      
      # 密码历史记录
      history:
        enabled: false
        history-size: 5
        retention-period: P365D
      
      # 密码过期
      expiration:
        enabled: false
        validity-period: P90D
        warning-days: 7
      
      # 审计日志
      audit:
        enabled: true
        log-successful-validation: false
        log-failed-validation: true
        log-password-change: true
        log-level: INFO