-- liquibase formatted sql

-- changeset whoiszxl:1
-- comment 课程模块: 初始化模块表结构

-- 课程主表
DROP TABLE IF EXISTS `cou_course`;
CREATE TABLE IF NOT EXISTS `cou_course`(
    `id`                        bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `course_code`               varchar(32) NOT NULL COMMENT '课程编码，唯一标识',
    `name`                      varchar(100) NOT NULL COMMENT '课程名称',
    `description`               text COMMENT '课程简介',
    `avatar`                    varchar(255) DEFAULT NULL COMMENT '课程封面小图',
    `cover_image`               varchar(255) DEFAULT NULL COMMENT '课程封面大图',
    `teacher_id`                bigint(20) NOT NULL COMMENT '讲师ID',
    `category_id`               bigint(20) DEFAULT NULL COMMENT '分类ID',
    `planet_id`                 bigint(20) DEFAULT NULL COMMENT '关联星球ID',
    `tags`                      varchar(500) DEFAULT NULL COMMENT '标签，逗号分隔',
    `price_type`                tinyint(1) UNSIGNED DEFAULT 1 COMMENT '价格类型: 1-免费 2-付费',
    `price`                     decimal(10,2) DEFAULT 0.00 COMMENT '课程价格',
    `original_price`            decimal(10,2) DEFAULT 0.00 COMMENT '原价',
    `discount_price`            decimal(10,2) DEFAULT 0.00 COMMENT '优惠价',
    `discount_start_time`       datetime DEFAULT NULL COMMENT '优惠开始时间',
    `discount_end_time`         datetime DEFAULT NULL COMMENT '优惠结束时间',
    `join_type`                 tinyint(1) UNSIGNED DEFAULT 1 COMMENT '加入方式: 1-直接加入 2-需要审核',
    `is_public`                 tinyint(1) UNSIGNED DEFAULT 1 COMMENT '是否公开: 0-私密 1-公开',
    `max_members`               int(11) DEFAULT 0 COMMENT '最大成员数，0表示无限制',
    `join_question`             text DEFAULT NULL COMMENT '加入问题',
    `auto_approve`              tinyint(1) UNSIGNED DEFAULT 1 COMMENT '是否自动通过申请: 0-否 1-是',
    `allow_member_post`         tinyint(1) UNSIGNED DEFAULT 1 COMMENT '是否允许成员发帖: 0-否 1-是',
    `post_need_approve`         tinyint(1) UNSIGNED DEFAULT 0 COMMENT '发帖是否需要审核: 0-否 1-是',
    `allow_anonymous`           tinyint(1) UNSIGNED DEFAULT 0 COMMENT '是否允许匿名发帖: 0-否 1-是',
    `watermark_enabled`         tinyint(1) UNSIGNED DEFAULT 0 COMMENT '是否开启水印: 0-否 1-是',
    `student_count`             int(11) DEFAULT 0 COMMENT '学生数量',
    `chapter_count`             int(11) DEFAULT 0 COMMENT '章节数量',
    `lesson_count`              int(11) DEFAULT 0 COMMENT '课时数量',
    `total_duration`            int(11) DEFAULT 0 COMMENT '总时长（分钟）',
    `view_count`                int(11) DEFAULT 0 COMMENT '浏览次数',
    `like_count`                int(11) DEFAULT 0 COMMENT '点赞数',
    `share_count`               int(11) DEFAULT 0 COMMENT '分享次数',
    `total_income`              decimal(15,2) DEFAULT 0.00 COMMENT '总收入',
    `hot_score`                 int(11) DEFAULT 0 COMMENT '热度分数',
    `quality_score`             decimal(3,1) DEFAULT 0.0 COMMENT '质量评分',
    `last_active_time`          datetime DEFAULT NULL COMMENT '最后活跃时间',
    `recommend_weight`          int(11) DEFAULT 0 COMMENT '推荐权重',
    `is_featured`               tinyint(1) UNSIGNED DEFAULT 0 COMMENT '是否精选: 0-否 1-是',
    `is_official`               tinyint(1) UNSIGNED DEFAULT 0 COMMENT '是否官方: 0-否 1-是',
    `difficulty_level`          tinyint(1) UNSIGNED DEFAULT 1 COMMENT '难度等级: 1-初级 2-中级 3-高级',
    `course_type`               tinyint(1) UNSIGNED DEFAULT 1 COMMENT '课程类型: 1-录播课程 2-直播课程 3-图文课程',
    `course_status`             tinyint(1) UNSIGNED DEFAULT 1 COMMENT '课程状态: 1-编辑中 2-审核中 3-已发布 4-已下架',
    `valid_start_time`          datetime DEFAULT NULL COMMENT '有效开始时间',
    `valid_end_time`            datetime DEFAULT NULL COMMENT '有效结束时间',
    `close_reason`              varchar(255) DEFAULT NULL COMMENT '关闭原因',
    `extra_config`              json DEFAULT NULL COMMENT '扩展配置，JSON格式',
    `course_intro`              text DEFAULT NULL COMMENT '课程介绍',
    `learning_objectives`       text DEFAULT NULL COMMENT '学习目标',
    `version`                   bigint(20) unsigned NOT NULL DEFAULT '1' COMMENT '乐观锁',
    `status`                    tinyint(1) UNSIGNED DEFAULT 1 COMMENT '业务状态: 0-禁用 1-启用 2-审核中 3-已关闭',
    `is_deleted`                tinyint(1) UNSIGNED DEFAULT 0 COMMENT '逻辑删除 1: 已删除， 0: 未删除',
    `created_by`                bigint(20) NOT NULL COMMENT '创建者',
    `updated_by`                bigint(20) DEFAULT NULL COMMENT '更新者',
    `created_at`                datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`                datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE INDEX `uk_course_code`(`course_code`) USING BTREE,
    INDEX `idx_teacher_id`(`teacher_id`) USING BTREE,
    INDEX `idx_category_id`(`category_id`) USING BTREE,
    INDEX `idx_planet_id`(`planet_id`) USING BTREE,
    INDEX `idx_price_type`(`price_type`) USING BTREE,
    INDEX `idx_status`(`status`) USING BTREE,
    INDEX `idx_is_public`(`is_public`) USING BTREE,
    INDEX `idx_hot_score`(`hot_score`) USING BTREE,
    INDEX `idx_created_at`(`created_at`) USING BTREE,
    INDEX `idx_student_count`(`student_count`) USING BTREE,
    INDEX `idx_course_status`(`course_status`) USING BTREE,
    INDEX `idx_difficulty_level`(`difficulty_level`) USING BTREE
) ENGINE = InnoDB CHARSET = utf8mb4 COMMENT = '课程表' ROW_FORMAT = Dynamic;

-- 课程章节表
DROP TABLE IF EXISTS `cou_chapter`;
CREATE TABLE IF NOT EXISTS `cou_chapter`(
    `id`                        bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `course_id`                 bigint(20) NOT NULL COMMENT '课程 ID',
    `title`                     varchar(100) NOT NULL COMMENT '章节标题',
    `description`               text COMMENT '章节描述',
    `sort_order`                int(11) DEFAULT 0 COMMENT '排序序号',
    `lesson_count`              int(11) DEFAULT 0 COMMENT '课时数量',
    `total_duration`            int(11) DEFAULT 0 COMMENT '章节总时长（分钟）',
    `is_free`                   tinyint(1) UNSIGNED DEFAULT 0 COMMENT '是否免费: 0-否 1-是',
    `version`                   bigint(20) unsigned NOT NULL DEFAULT '1' COMMENT '乐观锁',
    `status`                    tinyint(1) UNSIGNED DEFAULT 1 COMMENT '业务状态: 0-禁用 1-启用',
    `is_deleted`                tinyint(1) UNSIGNED DEFAULT 0 COMMENT '逻辑删除 1: 已删除， 0: 未删除',
    `created_by`                bigint(20) NOT NULL COMMENT '创建者',
    `updated_by`                bigint(20) DEFAULT NULL COMMENT '更新者',
    `created_at`                datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`                datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`) USING BTREE,
    INDEX `idx_course_id`(`course_id`) USING BTREE,
    INDEX `idx_sort_order`(`sort_order`) USING BTREE
) ENGINE = InnoDB CHARSET = utf8mb4 COMMENT = '课程章节表' ROW_FORMAT = Dynamic;

-- 课程内容表
DROP TABLE IF EXISTS `cou_lesson`;
CREATE TABLE IF NOT EXISTS `cou_lesson`(
    `id`                        bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `course_id`                 bigint(20) NOT NULL COMMENT '课程 ID',
    `chapter_id`                bigint(20) NOT NULL COMMENT '章节 ID',
    `title`                     varchar(100) NOT NULL COMMENT '课时标题',
    `description`               text COMMENT '课时描述',
    `content_type`              tinyint(1) UNSIGNED DEFAULT 1 COMMENT '内容类型: 1-视频 2-图文 3-音频 4-文档 5-代码',
    `content_url`               varchar(255) DEFAULT NULL COMMENT '内容URL',
    `video_duration`            int(11) DEFAULT 0 COMMENT '视频时长（秒）',
    `sort_order`                int(11) DEFAULT 0 COMMENT '排序序号',
    `is_free`                   tinyint(1) UNSIGNED DEFAULT 0 COMMENT '是否免费: 0-否 1-是',
    `is_trial`                  tinyint(1) UNSIGNED DEFAULT 0 COMMENT '是否试看: 0-否 1-是',
    `is_required`               tinyint(1) UNSIGNED DEFAULT 1 COMMENT '是否必修: 0-否 1-是',
    `resource_json`             json DEFAULT NULL COMMENT '资源信息JSON: 包含附件、代码地址、网盘地址等',
    `text_content`              longtext COMMENT '文本内容（图文课程用）',
    `code_repository`           varchar(255) DEFAULT NULL COMMENT '代码仓库地址',
    `netdisk_url`               varchar(255) DEFAULT NULL COMMENT '网盘地址',
    `netdisk_password`          varchar(20) DEFAULT NULL COMMENT '网盘提取码',
    `attachment_urls`           json DEFAULT NULL COMMENT '附件URL列表',
    `version`                   bigint(20) unsigned NOT NULL DEFAULT '1' COMMENT '乐观锁',
    `status`                    tinyint(1) UNSIGNED DEFAULT 1 COMMENT '业务状态: 0-禁用 1-启用',
    `is_deleted`                tinyint(1) UNSIGNED DEFAULT 0 COMMENT '逻辑删除 1: 已删除， 0: 未删除',
    `created_by`                bigint(20) NOT NULL COMMENT '创建者',
    `updated_by`                bigint(20) DEFAULT NULL COMMENT '更新者',
    `created_at`                datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`                datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`) USING BTREE,
    INDEX `idx_course_id`(`course_id`) USING BTREE,
    INDEX `idx_chapter_id`(`chapter_id`) USING BTREE,
    INDEX `idx_sort_order`(`sort_order`) USING BTREE,
    INDEX `idx_is_free`(`is_free`) USING BTREE
) ENGINE = InnoDB CHARSET = utf8mb4 COMMENT = '课程内容表' ROW_FORMAT = Dynamic;

-- 课程评价表
DROP TABLE IF EXISTS `cou_review`;
CREATE TABLE IF NOT EXISTS `cou_review`(
    `id`                        bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `course_id`                 bigint(20) NOT NULL COMMENT '课程 ID',
    `user_id`                   bigint(20) NOT NULL COMMENT '用户 ID',
    `rating`                    decimal(2,1) NOT NULL COMMENT '评分（1-5分）',
    `content`                   text COMMENT '评价内容',
    `pros`                      varchar(500) DEFAULT NULL COMMENT '优点',
    `cons`                      varchar(500) DEFAULT NULL COMMENT '缺点',
    `is_anonymous`              tinyint(1) UNSIGNED DEFAULT 0 COMMENT '是否匿名: 0-否 1-是',
    `like_count`                int(11) DEFAULT 0 COMMENT '点赞数',
    `reply_count`               int(11) DEFAULT 0 COMMENT '回复数',
    `is_featured`               tinyint(1) UNSIGNED DEFAULT 0 COMMENT '是否精选: 0-否 1-是',
    `teacher_reply`             text COMMENT '讲师回复',
    `teacher_reply_time`        datetime DEFAULT NULL COMMENT '讲师回复时间',
    `completion_rate`           decimal(5,2) DEFAULT NULL COMMENT '课程完成度（百分比）',
    `review_time`               datetime DEFAULT NULL COMMENT '评价时间',
    `version`                   bigint(20) unsigned NOT NULL DEFAULT '1' COMMENT '乐观锁',
    `status`                    tinyint(1) UNSIGNED DEFAULT 1 COMMENT '状态: 0-待审核 1-已发布 2-已隐藏',
    `is_deleted`                tinyint(1) UNSIGNED DEFAULT 0 COMMENT '逻辑删除 1: 已删除， 0: 未删除',
    `created_by`                bigint(20) NOT NULL COMMENT '创建者',
    `updated_by`                bigint(20) DEFAULT NULL COMMENT '更新者',
    `created_at`                datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`                datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`) USING BTREE,
    INDEX `idx_course_id`(`course_id`) USING BTREE,
    INDEX `idx_user_id`(`user_id`) USING BTREE,
    INDEX `idx_rating`(`rating`) USING BTREE,
    INDEX `idx_created_at`(`created_at`) USING BTREE
) ENGINE = InnoDB CHARSET = utf8mb4 COMMENT = '课程评价表' ROW_FORMAT = Dynamic;

-- 课程学习进度表
DROP TABLE IF EXISTS `cou_learning_progress`;
CREATE TABLE IF NOT EXISTS `cou_learning_progress`(
    `id`                        bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `course_id`                 bigint(20) NOT NULL COMMENT '课程 ID',
    `user_id`                   bigint(20) NOT NULL COMMENT '用户 ID',
    `lesson_id`                 bigint(20) NOT NULL COMMENT '课时 ID',
    `progress_percent`          decimal(5,2) DEFAULT 0.00 COMMENT '进度百分比',
    `watch_duration`            int(11) DEFAULT 0 COMMENT '观看时长（秒）',
    `last_position`             int(11) DEFAULT 0 COMMENT '上次观看位置（秒）',
    `is_completed`              tinyint(1) UNSIGNED DEFAULT 0 COMMENT '是否完成: 0-否 1-是',
    `completed_time`            datetime DEFAULT NULL COMMENT '完成时间',
    `watch_count`               int(11) DEFAULT 0 COMMENT '观看次数',
    `first_watch_time`          datetime DEFAULT NULL COMMENT '首次观看时间',
    `last_watch_time`           datetime DEFAULT NULL COMMENT '最近观看时间',
    `notes`                     text COMMENT '学习笔记',
    `version`                   bigint(20) unsigned NOT NULL DEFAULT '1' COMMENT '乐观锁',
    `status`                    tinyint(1) UNSIGNED DEFAULT 1 COMMENT '状态: 0-禁用 1-启用',
    `is_deleted`                tinyint(1) UNSIGNED DEFAULT 0 COMMENT '逻辑删除 1: 已删除， 0: 未删除',
    `created_by`                bigint(20) NOT NULL COMMENT '创建者',
    `updated_by`                bigint(20) DEFAULT NULL COMMENT '更新者',
    `created_at`                datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`                datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE INDEX `uk_user_lesson`(`user_id`, `lesson_id`) USING BTREE,
    INDEX `idx_course_id`(`course_id`) USING BTREE,
    INDEX `idx_user_id`(`user_id`) USING BTREE,
    INDEX `idx_lesson_id`(`lesson_id`) USING BTREE,
    INDEX `idx_is_completed`(`is_completed`) USING BTREE,
    INDEX `idx_last_watch_time`(`last_watch_time`) USING BTREE
) ENGINE = InnoDB CHARSET = utf8mb4 COMMENT = '课程学习进度表' ROW_FORMAT = Dynamic;

-- 课程分类表（参考星球分类表设计）
DROP TABLE IF EXISTS `cou_category`;
CREATE TABLE IF NOT EXISTS `cou_category`(
    `id`                        bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `category_name`             varchar(64) NOT NULL COMMENT '分类名称',
    `icon_url`                  varchar(255) NOT NULL COMMENT '分类图标链接',
    `parent_id`                 bigint(20) DEFAULT 0 COMMENT '父分类ID，0表示顶级分类',
    `level`                     tinyint(1) DEFAULT 1 COMMENT '分类级别:1->1级; 2->2级 3->3级',
    `sort`                      int(6) DEFAULT 1 COMMENT '排序,数值越大越靠前',
    `description`               varchar(500) DEFAULT NULL COMMENT '分类描述',
    `course_count`              int(11) DEFAULT 0 COMMENT '课程数量',
    `is_featured`               tinyint(1) UNSIGNED DEFAULT 0 COMMENT '是否推荐: 0-否 1-是',
    `version`                   bigint(20) unsigned NOT NULL DEFAULT '1' COMMENT '乐观锁',
    `status`                    tinyint(1) UNSIGNED DEFAULT 1 COMMENT '业务状态',
    `is_deleted`                tinyint(1) UNSIGNED DEFAULT 0 COMMENT '逻辑删除 1: 已删除， 0: 未删除',
    `created_by`                bigint(20) NOT NULL COMMENT '创建者',
    `updated_by`                bigint(20) DEFAULT NULL COMMENT '更新者',
    `created_at`                datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`                datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`) USING BTREE,
    INDEX `idx_parent_id`(`parent_id`) USING BTREE,
    INDEX `idx_sort`(`sort`) USING BTREE,
    INDEX `idx_level`(`level`) USING BTREE,
    INDEX `idx_is_featured`(`is_featured`) USING BTREE
) ENGINE = InnoDB CHARSET = utf8mb4 COMMENT = '课程分类表' ROW_FORMAT = Dynamic;

-- 证书模板表
DROP TABLE IF EXISTS `cou_certificate_template`;
CREATE TABLE IF NOT EXISTS `cou_certificate_template`(
    `id`                        bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `template_name`             varchar(100) NOT NULL COMMENT '模板名称',
    `template_code`             varchar(50) NOT NULL COMMENT '模板编码',
    `template_type`             tinyint(1) UNSIGNED DEFAULT 1 COMMENT '模板类型: 1-课程完成证书 2-考试通过证书 3-技能认证证书',
    `template_url`              varchar(255) NOT NULL COMMENT '模板文件URL',
    `preview_url`               varchar(255) DEFAULT NULL COMMENT '预览图URL',
    `template_config`           json DEFAULT NULL COMMENT '模板配置JSON: 包含字段位置、字体样式等',
    `is_default`                tinyint(1) UNSIGNED DEFAULT 0 COMMENT '是否默认模板: 0-否 1-是',
    `sort_order`                int(11) DEFAULT 0 COMMENT '排序序号',
    `description`               varchar(500) DEFAULT NULL COMMENT '模板描述',
    `version`                   bigint(20) unsigned NOT NULL DEFAULT '1' COMMENT '乐观锁',
    `status`                    tinyint(1) UNSIGNED DEFAULT 1 COMMENT '状态: 0-禁用 1-启用',
    `is_deleted`                tinyint(1) UNSIGNED DEFAULT 0 COMMENT '逻辑删除 1: 已删除， 0: 未删除',
    `created_by`                bigint(20) NOT NULL COMMENT '创建者',
    `updated_by`                bigint(20) DEFAULT NULL COMMENT '更新者',
    `created_at`                datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`                datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE INDEX `uk_template_code`(`template_code`) USING BTREE,
    INDEX `idx_template_type`(`template_type`) USING BTREE,
    INDEX `idx_is_default`(`is_default`) USING BTREE,
    INDEX `idx_sort_order`(`sort_order`) USING BTREE
) ENGINE = InnoDB CHARSET = utf8mb4 COMMENT = '证书模板表' ROW_FORMAT = Dynamic;

-- 课程证书表
DROP TABLE IF EXISTS `cou_certificate`;
CREATE TABLE IF NOT EXISTS `cou_certificate`(
    `id`                        bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `course_id`                 bigint(20) NOT NULL COMMENT '课程ID',
    `user_id`                   bigint(20) NOT NULL COMMENT '用户ID',
    `certificate_no`            varchar(50) NOT NULL COMMENT '证书编号',
    `certificate_name`          varchar(100) NOT NULL COMMENT '证书名称',
    `certificate_url`           varchar(255) DEFAULT NULL COMMENT '证书文件URL',
    `issue_date`                datetime DEFAULT CURRENT_TIMESTAMP COMMENT '颁发日期',
    `expire_date`               datetime DEFAULT NULL COMMENT '过期日期',
    `completion_rate`           decimal(5,2) DEFAULT 100.00 COMMENT '课程完成率',
    `score`                     decimal(5,2) DEFAULT NULL COMMENT '考试成绩',
    `template_id`               bigint(20) DEFAULT NULL COMMENT '证书模板ID',
    `extra_info`                json DEFAULT NULL COMMENT '额外信息JSON',
    `version`                   bigint(20) unsigned NOT NULL DEFAULT '1' COMMENT '乐观锁',
    `status`                    tinyint(1) UNSIGNED DEFAULT 1 COMMENT '状态: 1-有效 2-已撤销 3-已过期',
    `is_deleted`                tinyint(1) UNSIGNED DEFAULT 0 COMMENT '逻辑删除 1: 已删除， 0: 未删除',
    `created_by`                bigint(20) NOT NULL COMMENT '创建者',
    `updated_by`                bigint(20) DEFAULT NULL COMMENT '更新者',
    `created_at`                datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`                datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE INDEX `uk_certificate_no`(`certificate_no`) USING BTREE,
    UNIQUE INDEX `uk_course_user`(`course_id`, `user_id`) USING BTREE,
    INDEX `idx_user_id`(`user_id`) USING BTREE,
    INDEX `idx_issue_date`(`issue_date`) USING BTREE
) ENGINE = InnoDB CHARSET = utf8mb4 COMMENT = '课程证书表' ROW_FORMAT = Dynamic;

-- 课程作业表
DROP TABLE IF EXISTS `cou_assignment`;
CREATE TABLE IF NOT EXISTS `cou_assignment`(
    `id`                        bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `course_id`                 bigint(20) NOT NULL COMMENT '课程ID',
    `chapter_id`                bigint(20) DEFAULT NULL COMMENT '章节ID',
    `lesson_id`                 bigint(20) DEFAULT NULL COMMENT '课时ID',
    `title`                     varchar(100) NOT NULL COMMENT '作业标题',
    `description`               text COMMENT '作业描述',
    `content`                   longtext COMMENT '作业内容',
    `assignment_type`           tinyint(1) UNSIGNED DEFAULT 1 COMMENT '作业类型: 1-编程作业 2-文档作业 3-项目作业 4-测验',
    `difficulty_level`          tinyint(1) UNSIGNED DEFAULT 1 COMMENT '难度等级: 1-简单 2-中等 3-困难',
    `max_score`                 decimal(5,2) DEFAULT 100.00 COMMENT '满分',
    `pass_score`                decimal(5,2) DEFAULT 60.00 COMMENT '及格分',
    `time_limit`                int(11) DEFAULT NULL COMMENT '时间限制（分钟）',
    `max_attempts`              int(11) DEFAULT 3 COMMENT '最大尝试次数',
    `start_time`                datetime DEFAULT NULL COMMENT '开始时间',
    `end_time`                  datetime DEFAULT NULL COMMENT '结束时间',
    `is_required`               tinyint(1) UNSIGNED DEFAULT 1 COMMENT '是否必做: 0-否 1-是',
    `auto_grade`                tinyint(1) UNSIGNED DEFAULT 0 COMMENT '是否自动评分: 0-否 1-是',
    `reference_answer`          longtext COMMENT '参考答案',
    `grading_criteria`          json DEFAULT NULL COMMENT '评分标准JSON',
    `attachment_urls`           json DEFAULT NULL COMMENT '附件URL列表',
    `version`                   bigint(20) unsigned NOT NULL DEFAULT '1' COMMENT '乐观锁',
    `status`                    tinyint(1) UNSIGNED DEFAULT 1 COMMENT '状态: 0-草稿 1-发布 2-关闭',
    `is_deleted`                tinyint(1) UNSIGNED DEFAULT 0 COMMENT '逻辑删除 1: 已删除， 0: 未删除',
    `created_by`                bigint(20) NOT NULL COMMENT '创建者',
    `updated_by`                bigint(20) DEFAULT NULL COMMENT '更新者',
    `created_at`                datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`                datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`) USING BTREE,
    INDEX `idx_course_id`(`course_id`) USING BTREE,
    INDEX `idx_chapter_id`(`chapter_id`) USING BTREE,
    INDEX `idx_lesson_id`(`lesson_id`) USING BTREE,
    INDEX `idx_assignment_type`(`assignment_type`) USING BTREE,
    INDEX `idx_start_time`(`start_time`) USING BTREE,
    INDEX `idx_end_time`(`end_time`) USING BTREE
) ENGINE = InnoDB CHARSET = utf8mb4 COMMENT = '课程作业表' ROW_FORMAT = Dynamic;

-- 作业提交表
DROP TABLE IF EXISTS `cou_assignment_submission`;
CREATE TABLE IF NOT EXISTS `cou_assignment_submission`(
    `id`                        bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `assignment_id`             bigint(20) NOT NULL COMMENT '作业ID',
    `user_id`                   bigint(20) NOT NULL COMMENT '用户ID',
    `submission_content`        longtext COMMENT '提交内容',
    `attachment_urls`           json DEFAULT NULL COMMENT '附件URL列表',
    `code_repository`           varchar(255) DEFAULT NULL COMMENT '代码仓库地址',
    `submit_time`               datetime DEFAULT CURRENT_TIMESTAMP COMMENT '提交时间',
    `score`                     decimal(5,2) DEFAULT NULL COMMENT '得分',
    `grade_time`                datetime DEFAULT NULL COMMENT '评分时间',
    `grader_id`                 bigint(20) DEFAULT NULL COMMENT '评分人ID',
    `feedback`                  text COMMENT '评分反馈',
    `attempt_count`             int(11) DEFAULT 1 COMMENT '尝试次数',
    `is_passed`                 tinyint(1) UNSIGNED DEFAULT 0 COMMENT '是否通过: 0-否 1-是',
    `grade_status`              tinyint(1) UNSIGNED DEFAULT 1 COMMENT '评分状态: 1-待评分 2-已评分 3-需重做',
    `version`                   bigint(20) unsigned NOT NULL DEFAULT '1' COMMENT '乐观锁',
    `status`                    tinyint(1) UNSIGNED DEFAULT 1 COMMENT '状态: 1-已提交 2-已评分 3-已退回',
    `is_deleted`                tinyint(1) UNSIGNED DEFAULT 0 COMMENT '逻辑删除 1: 已删除， 0: 未删除',
    `created_by`                bigint(20) NOT NULL COMMENT '创建者',
    `updated_by`                bigint(20) DEFAULT NULL COMMENT '更新者',
    `created_at`                datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`                datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`) USING BTREE,
    INDEX `idx_assignment_id`(`assignment_id`) USING BTREE,
    INDEX `idx_user_id`(`user_id`) USING BTREE,
    INDEX `idx_submit_time`(`submit_time`) USING BTREE,
    INDEX `idx_grade_status`(`grade_status`) USING BTREE,
    INDEX `idx_is_passed`(`is_passed`) USING BTREE
) ENGINE = InnoDB CHARSET = utf8mb4 COMMENT = '作业提交表' ROW_FORMAT = Dynamic;

-- 课程报名表
DROP TABLE IF EXISTS `cou_enrollment`;
CREATE TABLE IF NOT EXISTS `cou_enrollment`(
    `id`                        bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `course_id`                 bigint(20) NOT NULL COMMENT '课程ID',
    `user_id`                   bigint(20) NOT NULL COMMENT '用户ID',
    `order_id`                  bigint(20) DEFAULT NULL COMMENT '订单ID',
    `enrollment_type`           tinyint(1) UNSIGNED DEFAULT 1 COMMENT '报名类型: 1-付费 2-免费 3-兑换 4-赠送',
    `enrollment_time`           datetime DEFAULT CURRENT_TIMESTAMP COMMENT '报名时间',
    `expire_time`               datetime DEFAULT NULL COMMENT '到期时间',
    `learning_progress`         decimal(5,2) DEFAULT 0.00 COMMENT '学习进度百分比',
    `last_study_time`           datetime DEFAULT NULL COMMENT '最后学习时间',
    `total_study_duration`      int(11) DEFAULT 0 COMMENT '总学习时长（分钟）',
    `completed_lessons`         int(11) DEFAULT 0 COMMENT '已完成课时数',
    `total_lessons`             int(11) DEFAULT 0 COMMENT '总课时数',
    `certificate_issued`        tinyint(1) UNSIGNED DEFAULT 0 COMMENT '是否已颁发证书: 0-否 1-是',
    `source`                    varchar(50) DEFAULT NULL COMMENT '报名来源',
    `version`                   bigint(20) unsigned NOT NULL DEFAULT '1' COMMENT '乐观锁',
    `status`                    tinyint(1) UNSIGNED DEFAULT 1 COMMENT '状态: 1-学习中 2-已完成 3-已过期 4-已退课',
    `is_deleted`                tinyint(1) UNSIGNED DEFAULT 0 COMMENT '逻辑删除 1: 已删除， 0: 未删除',
    `created_by`                bigint(20) NOT NULL COMMENT '创建者',
    `updated_by`                bigint(20) DEFAULT NULL COMMENT '更新者',
    `created_at`                datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`                datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE INDEX `uk_course_user`(`course_id`, `user_id`) USING BTREE,
    INDEX `idx_user_id`(`user_id`) USING BTREE,
    INDEX `idx_enrollment_time`(`enrollment_time`) USING BTREE,
    INDEX `idx_expire_time`(`expire_time`) USING BTREE,
    INDEX `idx_status`(`status`) USING BTREE
) ENGINE = InnoDB CHARSET = utf8mb4 COMMENT = '课程报名表' ROW_FORMAT = Dynamic;

