# JetCache 配置示例
haha:
  cache:
    jetcache:
      # 是否启用 JetCache
      enabled: true
      # 统计间隔时间（分钟）
      stat-interval-minutes: 15
      # 是否隐藏包名
      hide-packages: true
      
      # 本地缓存配置
      local:
        # 缓存类型：caffeine, linkedhashmap
        type: caffeine
        # 默认过期时间
        default-expire: 30m
        # 最大缓存数量
        limit: 10000
        # key 转换器
        key-convertor: fastjson2
      
      # 远程缓存配置
      remote:
        # 缓存类型：redis.lettuce, redis.jedis
        type: redis.lettuce
        # 默认过期时间
        default-expire: 1h
        # key 转换器
        key-convertor: fastjson2
        # value 序列化器
        value-encoder: fastjson2
        # value 反序列化器
        value-decoder: fastjson2
        # key 前缀
        key-prefix: "haha:cache:"
        # 是否广播本地缓存失效消息
        broadcast-channel: true
      
      # 缓存区域配置
      areas:
        # 用户缓存区域
        user:
          local:
            type: caffeine
            default-expire: 10m
            limit: 5000
          remote:
            type: redis.lettuce
            default-expire: 30m
            key-prefix: "haha:user:"
            broadcast-channel: true
        
        # 系统缓存区域
        system:
          local:
            type: caffeine
            default-expire: 1h
            limit: 1000
          remote:
            type: redis.lettuce
            default-expire: 6h
            key-prefix: "haha:system:"
            broadcast-channel: false

# Redis 配置（JetCache 依赖）
spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms